apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nagp-api
  template:
    metadata:
      labels:
        app: nagp-api
    spec:
      containers:
      - name: nagp-api
        image: brijdocker88/nagp-api:v1
        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          value: nagap_database

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password